services:
  flipforce-db:
    image: postgres:15
    container_name: flipforce-db
    restart: always
    environment:
      POSTGRES_DB: ${FLIPFORCE_POSTGRES_DB}
      POSTGRES_USER: ${FLIPFORCE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FLIPFORCE_POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${FLIPFORCE_POSTGRES_PORT_ON_HOST}:5432" # Renamed for clarity if needed, though 5432 is standard internally

  tracker:
    build:
      context: ./backend/tracker
    container_name: flipforce-tracker
    restart: always
    env_file:
      - .env # This file should now contain FLIPFORCE_ prefixed variables
    depends_on:
      - flipforce-db
    working_dir: /app

  dashboard:
    build:
      context: ./dashboard
    container_name: flipforce-dashboard
    restart: always
    env_file:
      - .env # This file should now contain FLIPFORCE_ prefixed variables
    ports:
      - "8050:8050"
    depends_on:
      - flipforce-db
    working_dir: /app

volumes:
  pgdata: